### ISSUE TITLE
ValueError with tensor shape

### ISSUE THREAD

**Issue by vikas95** [HsiaoYetGun/Decomposable-Attention#1]
Hi,

Thanks for sharing the tensorflow version of Decomp-att, this a very useful resource. I am getting a small error and would be very thankful if you can help me in solving this.

While running python3 Train.py, I am getting the following error:

Start training and evaluating ...
Epoch :  1
Traceback (most recent call last):
  File "Train.py", line 164, in <module>
    train()
  File "Train.py", line 93, in train
    _, batch_loss, batch_acc = sess.run([model.train, model.loss, model.acc], feed_dict=feed_dict)
  File "/Users/vikasy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/Users/vikasy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1086, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (128,) for Tensor 'premise_mask:0', which has shape '(?, 100)'

Looking forward for your reply.
Thanks,
vikasy95

**Comment by nnn1988** [comment]
HI
I have the same error !!!

**Comment by duongkstn** [comment]
any solutions ?
